"""TASK-0172 -- spectrum-preserving Hamiltonian reduction: a controlled
alternative to `coarse.coarse_grain`'s lossy Louvain/spectral community
merging, with a quantitative retention proof rather than an assumed one.

Two label-blind reduction methods, both applied directly to the existing
`H_new` (diagonal potential terms retained, unlike `coarse._graph_weights`,
which drops them):

  krylov_basis  : the Krylov subspace generated by the active-site seed,
                  `span{H^k e_i : i in seed_idx, k=0,1,...}` -- exact for
                  the seeded dynamics at fixed subspace dimension (Novo,
                  Chakraborty, Mohseni, Neven & Omar 2015, *Sci. Rep.* 5,
                  13304, "Systematic Dimensionality Reduction for Quantum
                  Walks" -- verified against the actual paper before
                  building, TASK-0172's own Constraint). Built here by
                  direct matrix powers + QR rather than the textbook
                  three-term block-Lanczos recurrence -- mathematically
                  the same invariant subspace (Krylov subspaces are
                  defined by their span, not by how a basis for them is
                  computed), a deliberate simplification justified by
                  scale (N <= ~700, m <= ~20: direct powers + one QR is
                  cheap and numerically unremarkable at this size; the
                  three-term recurrence exists mainly for much larger
                  problems where storing all Krylov vectors at once is
                  infeasible, which does not apply here) -- verified
                  empirically (this module's own test suite), not just
                  asserted equivalent.

  schur_complement : Loewdin/Feshbach partitioning -- split into a
                  retained set P and eliminated set Q, and return the
                  *exact* effective operator on P at a fixed reference
                  energy `H_eff(E) = H_PP + H_PQ (E - H_QQ)^-1 H_QP`
                  (Loewdin 1962, *J. Math. Phys.* 3(5), 969-982;
                  Feshbach 1962, *Ann. Phys.* 19(2), 287-313 -- both
                  verified against the actual papers before building).
                  Exact for H's own eigenpairs whose eigenvalue equals E
                  exactly; an energy-independent-effective-Hamiltonian
                  approximation for every other eigenvalue (Implementer's
                  call, TASK-0172's own Open Question: fixed reference
                  energy, not self-consistent -- E=0.0 default, matching
                  `transport.transmission_from_source`'s own "DC/zero-
                  bias limit" convention, not tuned against anything).

Both methods return objects an existing consumer (`time_averaged_
ctqw_converged`, `metrics.auc`/`precision_at_k`) can score directly, via
the `lift_*` functions below that embed the reduced operator's own
eigenvectors back into the original N-residue space -- so retention can
be measured as a real ranking/AUC/fidelity comparison against the full
system, not just an abstract subspace-quality number.
"""
from __future__ import annotations

import numpy as np


def krylov_basis(H: np.ndarray, seed_idx, m: int) -> np.ndarray:
    """Orthonormal basis `Q` (N, m_actual) for the Krylov subspace
    `span{H^k e_i : i in seed_idx, k=0,1,...}`, truncated to at most `m`
    columns. `m_actual <= m` if the subspace is rank-deficient before
    reaching `m` (e.g. a small disconnected component, or `m` larger
    than the graph itself) -- reported via the returned array's own
    shape, never silently padded.

    Built by generating candidate vectors in round-robin power order
    (`e_i`, then `H e_i` for every seed `i`, then `H^2 e_i`, ...) so that
    a truncation at any point still returns a valid (if smaller)
    Krylov-type subspace rather than exhausting one seed's full power
    sequence before starting the next, then a single QR decomposition
    with deflation of near-zero-norm (linearly dependent) columns via
    the diagonal of `R` -- `np.linalg.qr`'s own column-pivoting-free
    default is fine here since deflation is detected after the fact
    (small `|R_ii|`), not relied on to reorder columns.
    """
    seed_idx = np.atleast_1d(np.asarray(seed_idx, dtype=int))
    N = H.shape[0]
    n_seed = len(seed_idx)

    candidates = []
    current = np.zeros((N, n_seed))
    for j, i in enumerate(seed_idx):
        current[i, j] = 1.0
    while len(candidates) < m:
        for j in range(n_seed):
            candidates.append(current[:, j].copy())
        current = H @ current

    M = np.column_stack(candidates[: max(m, n_seed)])
    Q, R = np.linalg.qr(M)
    diag_r = np.abs(np.diag(R))
    keep = diag_r > 1e-10 * max(diag_r.max(), 1.0)
    Q = Q[:, keep]
    if Q.shape[1] > m:
        Q = Q[:, :m]
    return Q


def reduce_krylov(H: np.ndarray, Q: np.ndarray) -> np.ndarray:
    """The reduced operator `Q^T H Q` (m, m) -- Ritz-space Hamiltonian.
    Hermitian by construction whenever `H` is (checked, not assumed, by
    this module's own test suite)."""
    return Q.T @ H @ Q


def lift_krylov_eigvecs(Q: np.ndarray, w_local: np.ndarray, v_local: np.ndarray) -> tuple:
    """Embed the reduced operator's own eigenpairs back into the
    original N-residue space: `v_full = Q @ v_local` (Ritz vectors).
    Exactly unit-normalized already (`Q` and `v_local` are both
    orthonormal, so `Q @ v_local` is too) -- no renormalization needed,
    unlike `lift_schur_eigvecs`."""
    return w_local, Q @ v_local


def schur_complement(
    H: np.ndarray, retain_idx, E: float = 0.0, eta: float = None,
) -> tuple:
    """The exact Loewdin/Feshbach effective operator on `retain_idx` at
    reference energy `E`: `H_eff = H_PP + H_PQ (E + i*eta - H_QQ)^-1 H_QP`.

    `eta`: small regularization added to avoid an exact singularity if
    `E` happens to land on an eigenvalue of `H_QQ` -- same convention and
    default (`1e-6 * bandwidth`) as `transport.transmission_from_source`'s
    own `eta_reg`, not invented fresh. The returned `H_eff` is complex if
    `eta != 0`; callers that need a real, Hermitian operator (this
    module's own retention-metric callers) should pass `eta=0.0`
    explicitly once they've confirmed `E` is not resonant with `H_QQ`'s
    spectrum for their specific `retain_idx`/`E`, or accept the tiny
    imaginary part and take `.real` -- both are valid, documented choices,
    not silently decided here.

    Returns `(H_eff, elim_idx)` -- `elim_idx` (the eliminated-set index
    array) is needed by `lift_schur_eigvecs` and is cheap to recompute,
    but returned directly so every caller uses the identical ordering.

    `retain_idx` is sorted internally (ascending) regardless of the order
    passed in -- `H_eff`'s row/column `i` is then always
    `sorted(retain_idx)[i]`'s original residue, a fixed, predictable
    convention (position = `np.searchsorted(sorted(retain_idx), original_
    index)`) rather than depending on whatever order the caller happened
    to list residues in, which would silently permute `H_eff` relative to
    what a caller comparing it against the original residue ordering
    would expect.
    """
    retain_idx = np.sort(np.atleast_1d(np.asarray(retain_idx, dtype=int)))
    N = H.shape[0]
    all_idx = np.arange(N)
    elim_idx = np.setdiff1d(all_idx, retain_idx)

    H_PP = H[np.ix_(retain_idx, retain_idx)]
    if len(elim_idx) == 0:
        return H_PP, elim_idx

    H_PQ = H[np.ix_(retain_idx, elim_idx)]
    H_QP = H[np.ix_(elim_idx, retain_idx)]
    H_QQ = H[np.ix_(elim_idx, elim_idx)]

    if eta is None:
        w_full = np.linalg.eigvalsh(H)
        bandwidth = float(w_full[-1] - w_full[0])
        eta = 1e-6 * bandwidth if bandwidth > 0 else 1e-6

    M = (E + 1j * eta) * np.eye(len(elim_idx)) - H_QQ
    correction = H_PQ @ np.linalg.solve(M, H_QP)
    H_eff = H_PP + correction
    if eta == 0.0:
        H_eff = H_eff.real
    return H_eff, elim_idx


def lift_schur_eigvecs(
    H: np.ndarray, retain_idx: np.ndarray, elim_idx: np.ndarray,
    E: float, w_local: np.ndarray, v_local: np.ndarray, eta: float = 0.0,
) -> tuple:
    """Embed `H_eff(E)`'s own eigenvectors back into the original
    N-residue space using the exact elimination relation implied by the
    Schur complement's own derivation: for a state exactly at energy `E`,
    `psi_Q = (E - H_QQ)^-1 H_QP psi_P`. Applied here to every Ritz
    eigenvector at its own eigenvalue `w_local[i]` rather than strictly
    at `E` -- an approximation away from `E` itself (same "energy-
    independent effective Hamiltonian" caveat `schur_complement`'s own
    docstring states), stated explicitly, not hidden. Each lifted vector
    is renormalized to unit L2 norm (unlike `lift_krylov_eigvecs`, this
    lift is not automatically normalized).

    `retain_idx` is sorted internally, matching `schur_complement`'s own
    convention -- pass the same (unsorted-or-not) `retain_idx` array to
    both functions and the row/column convention stays consistent."""
    retain_idx = np.sort(np.atleast_1d(np.asarray(retain_idx, dtype=int)))
    N = H.shape[0]
    m = len(w_local)
    v_full = np.zeros((N, m))

    if len(elim_idx) == 0:
        v_full[retain_idx, :] = v_local
        return w_local, v_full

    H_PQ = H[np.ix_(retain_idx, elim_idx)]
    H_QP = H[np.ix_(elim_idx, retain_idx)]
    H_QQ = H[np.ix_(elim_idx, elim_idx)]

    v_full[retain_idx, :] = v_local
    for i in range(m):
        M = (w_local[i] + 1j * eta) * np.eye(len(elim_idx)) - H_QQ
        psi_Q = np.linalg.solve(M, H_QP @ v_local[:, i])
        if eta == 0.0:
            psi_Q = psi_Q.real
        v_full[elim_idx, i] = psi_Q
        norm = np.linalg.norm(v_full[:, i])
        if norm > 1e-300:
            v_full[:, i] /= norm

    return w_local, v_full
